session_config:
  session_id: facnn_fedavg_niid10_aws
  use_gpu: False
  aggregator: fedavg 
  aggregator_args: None
  client_selection: fedavg
  client_selection_args:
    client_fraction: 1.0
  checkpoint_interval: 1000
  validation_round_interval: 1
  generate_plots: False

benchmark_config:
  skip_benchmark: True
  model_id: FedAT_CNN
  model_dir: ./models/FedAT_CNN
  model_class: FedAT_CNN
  dataset: CIFAR100NIID10
  bench_minibatch_count: 500
  batch_size: 16
  learning_rate: 0.0001
  timeout_duration_s: 180

server_training_config:
  model_dir: ./models/FedAT_CNN
  global_model_validation_batch_size: 100
  num_training_rounds: 5

client_training_config:
  model_id: FedAT_CNN
  model_class: FedAT_CNN
  dataset: CIFAR100NIID10
  epochs: 1
  batch_size: 128
  learning_rate: 0.0005
  train_timeout_duration_s: 600
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True

model_config:
  use_custom_dataloader: True
  custom_loader_args:
    batch_size: 128

  use_custom_trainer: True
  custom_trainer_args:
    lr: 0.0005

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 100

