session_config:
  session_id: lenet_fedat_iid
  use_gpu: False
  aggregator: fedat
  aggregator_args: None
  client_selection: fedat
  client_selection_args:
    num_tiers: 3
    num_clients_selected_per_tier: 2
  checkpoint_interval: 100
  validation_round_interval: 1
  generate_plots: False

benchmark_config:
  skip_benchmark: False
  model_id: LeNet5
  model_dir: ./models/LeNet5
  model_class: LeNet5_class
  dataset: EMNIST_IID
  bench_minibatch_count: 500
  batch_size: 16
  learning_rate: 0.001
  timeout_duration_s: 180

server_training_config:
  model_dir: ./models/LeNet5
  global_model_validation_batch_size: 100
  num_training_rounds: 250

client_training_config:
  model_id: LeNet5
  model_class: LeNet5_class
  dataset: EMNIST_IID
  epochs: 1
  batch_size: 16
  learning_rate: 0.00005
  train_timeout_duration_s: 300
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True

model_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10 

