session_config:
  session_id: mobilenet_cifar10_fedasync_iid
  use_gpu: True
  aggregator: fedasync
  aggregator_args:
    alpha: 0.9
  client_selection: fedasync
  client_selection_args:
    client_fraction: 0.5
  checkpoint_interval: 10
  validation_round_interval: 1
  generate_plots: False

benchmark_config:
  model_id: MobileNet
  model_dir: ./models/MobileNet
  model_class: MobileNet
  dataset: CIFAR10
  bench_minibatch_count: 500
  batch_size: 8
  learning_rate: 0.0001
  timeout_duration_s: 20

server_training_config:
  model_dir: ./models/MobileNet
  global_model_validation_batch_size: 32
  num_training_rounds: 400

client_training_config:
  model_id: MobileNet
  model_class: MobileNet
  dataset: CIFAR10
  epochs: 5
  batch_size: 8
  learning_rate: 0.0001
  train_timeout_duration_s: 1200
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True

model_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10
    dropout: 0.2
